version: '3.9'
services:
  app:
      image: be-student-app
      context: .
      dockerfile: Dockerfile
      ports:
      - "8000:80"
      environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: students
      DB_USERNAME: root
      DB_PASSWORD: root
      APP_DEBUG: true

  depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: students
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    
volumes:
  db_data:
